import { Mentor } from './types'

export const mentors: Mentor[] = [
  {
    id: "1",
    name: "AM Trades",
    handle: "@amtrades",
    profileImage: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/AMTrades_profile-xVYIKkoc3Yyt0lErLM7sLu8UrnhLAp.jpeg",
    community: "The Market Lens",
    communityLink: "https://tradethelens.com/",
    markets: ["Futures", "Indices"],
    experience: "5+ years",
    liveTrades: true,
    bestKnownFor: "Weekly Profiles & Minimalist Charts",
    tradingStyle: ["Day Trading"],
    verified: true,
  },
  {
    id: "2",
    name: "TTrades",
    handle: "@ttrades_edu",
    profileImage: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/ttrades-Pqj3TvHpnh3lXxn59AT4zpf8dj5yv4.png",
    community: "The Market Lens",
    communityLink: "https://themarketlens.com",
    markets: ["Futures", "Indices"],
    experience: "7+ years",
    liveTrades: true,
    bestKnownFor: "Market Analysis",
    tradingStyle: ["Technical Analysis"],
    verified: true,
  },
  {
    id: "3",
    name: "TJR",
    handle: "@tjr_trades",
    profileImage: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/tjr-3Z1dboGJHJkVeOK5VAtCXpr1UP8Dhv.png",
    community: "TJR Trading",
    communityLink: "https://tjrtrading.com",
    markets: ["Futures", "Indices"],
    experience: "5+ years",
    liveTrades: true,
    bestKnownFor: "Price Action Trading",
    tradingStyle: ["Day Trading", "Scalping"],
    verified: true
  },
  {
    id: "4",
    name: "Patrick Wieland",
    handle: "@patrick_wieland",
    profileImage: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Wieland_patrick-nhSsYHkd0AIDlZaqyUHeqEvvfDC7IJ.png",
    community: "Wieland Trading",
    communityLink: "https://wielandtrading.com",
    markets: ["Futures", "Forex"],
    experience: "6+ years",
    liveTrades: true,
    bestKnownFor: "Livestreaming on Youtube, trolling ICT",
    tradingStyle: ["Day Trading", "Technical Analysis"],
    verified: true
  },
  {
    id: "5",
    name: "Tori",
    handle: "@toricrypto",
    profileImage: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/tori-btViiF56zUn8AJyGoygCK3lBBUQk2R.png",
    community: "Tori's Trading Room",
    communityLink: "https://toristradingroom.com",
    markets: ["Crypto"],
    experience: "4+ years",
    liveTrades: true,
    bestKnownFor: "Crypto Analysis",
    tradingStyle: ["Swing Trading"],
    verified: true
  },
  {
    id: "6",
    name: "Tanja",
    handle: "@tanjatrading",
    profileImage: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/tanja-pJi7sNJbr0sNtTyH8XqxlbSS5rgQeS.png",
    community: "Trading with Tanja",
    communityLink: "https://tradingwithtanja.com",
    markets: ["Forex", "Indices"],
    experience: "6+ years",
    liveTrades: true,
    bestKnownFor: "Price Action Trading",
    tradingStyle: ["Day Trading"],
    verified: true
  },
  {
    id: "7",
    name: "Kane",
    handle: "@kane_trades",
    profileImage: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/kane_mentor-YbLW2ybzl6XjPThJ3i0w67hTnkqgXu.png",
    community: "The Lab",
    communityLink: "https://kanestradingacademy.com",
    markets: ["Crypto", "Futures"],
    experience: "6+ years",
    liveTrades: true,
    bestKnownFor: "Market Analysis",
    tradingStyle: ["Day Trading"],
    verified: true
  },
  {
    id: "8",
    name: "Justin",
    handle: "@justintrading",
    profileImage: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/justin-qM4X7Y0m6qLjEHF6TDE3dv61jWtReP.png",
    community: "Tactical Traders",
    communityLink: "https://justintradingcommunity.com",
    markets: ["Futures", "Forex"],
    experience: "5+ years",
    liveTrades: true,
    bestKnownFor: "Technical Analysis",
    tradingStyle: ["Day Trading"],
    verified: true
  },
  {
    id: "9",
    name: "Lance Breitstein",
    handle: "@lancebreitstein",
    profileImage: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/lance-breitstein-GbTeXoSK8kyqnTs4Yx42NfIlr9NKW6.png",
    community: "Breitstein Trading",
    communityLink: "https://breitsteintrading.com",
    markets: ["Futures", "Forex"],
    experience: "8+ years",
    liveTrades: true,
    bestKnownFor: "Price Action & Market Structure",
    tradingStyle: ["Technical Analysis", "Price Action"],
    verified: true
  },
  {
    id: "10",
    name: "Jay Pelle",
    handle: "@jaypelle",
    profileImage: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/jaypelle-a9LuDGSIKUCwnApx8kNgCzq0aUBswH.png",
    community: "Pelle Trading",
    communityLink: "https://pelletrading.com",
    markets: ["Stocks", "Options"],
    experience: "7+ years",
    liveTrades: true,
    bestKnownFor: "Options Strategies",
    tradingStyle: ["Swing Trading", "Options Flow"],
    verified: true
  },
  {
    id: "11",
    name: "Humbled Trader",
    handle: "@humbledtrader",
    profileImage: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/humbledtrader-HLuqTUxaUQNuCnKMgDVyHuHuRGwrXA.png",
    community: "Humbled Trading",
    communityLink: "https://humbledtrading.com",
    markets: ["Stocks", "Options"],
    experience: "6+ years",
    liveTrades: true,
    bestKnownFor: "Day Trading Education",
    tradingStyle: ["Day Trading", "Swing Trading"],
    verified: true
  },
  {
    id: "12",
    name: "Casper",
    handle: "@caspertrading",
    profileImage: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/casper-F4RrSEzD6946WV9Nl8CdjTOrpj9K59.png",
    community: "Casper's Trading Hub",
    communityLink: "https://caspertradinghub.com",
    markets: ["Stocks", "Options"],
    experience: "5+ years",
    liveTrades: true,
    bestKnownFor: "Risk Management",
    tradingStyle: ["Technical Analysis", "Risk Management"],
    verified: true
  },
  {
    id: "13",
    name: "Brian Stonk",
    handle: "@brianstonk",
    profileImage: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/brianstonk_profile-CHplLUR5VwxjFauYk32eBSD9xoeKcw.png",
    community: "Stonk Trading",
    communityLink: "https://stonktrading.com",
    markets: ["Crypto", "Stocks"],
    experience: "4+ years",
    liveTrades: true,
    bestKnownFor: "Technical Analysis",
    tradingStyle: ["Swing Trading", "Day Trading"],
    verified: true
  },
  {
    id: "14",
    name: "Trades By Matt",
    handle: "@TradesByMatt",
    profileImage: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/TradesByMatt-Mah5MCYF7mYFsJdUsVqhVVodlprDX2.png",
    community: "Beats The Market",
    communityLink: "https://beatsthemarket.com",
    markets: ["Futures", "Indices"],
    experience: "5+ years",
    liveTrades: true,
    bestKnownFor: "Market Structure",
    tradingStyle: ["Day Trading", "Scalping"],
    verified: true
  },
  {
    id: "15",
    name: "Lethality",
    handle: "@lethality_trading",
    profileImage: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/lethality-VVNElXpl4PMKctS24nbAzHIWSZ8ry3.jpg",
    community: "Lethality Trading",
    communityLink: "https://lethalitytrading.com",
    markets: ["Forex", "Indices"],
    experience: "6+ years",
    liveTrades: true,
    bestKnownFor: "Technical Analysis",
    tradingStyle: ["Scalping", "Day Trading"],
    verified: true
  },
  {
    id: "16",
    name: "Amas",
    handle: "@amas_trading",
    profileImage: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Amas-RdPNnGOdMUBzTok7dAEpeDVjESfLjM.png",
    community: "Amas Trading",
    communityLink: "https://amastrading.com",
    markets: ["Crypto", "Stocks"],
    experience: "4+ years",
    liveTrades: true,
    bestKnownFor: "Crypto Analysis",
    tradingStyle: ["Swing Trading", "Day Trading"],
    verified: true
  },
  {
    id: "18",
    name: "Dante",
    handle: "@dante_trades",
    profileImage: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/dante-9t8zWwH89WxCC1yknE3TxHGQpUTnjZ.png",
    community: "Dante's Trading Room",
    communityLink: "https://dantestradingroom.com",
    markets: ["Stocks", "Options"],
    experience: "6+ years",
    liveTrades: true,
    bestKnownFor: "Options Strategies",
    tradingStyle: ["Day Trading", "Options Flow"],
    verified: true
  },
  {
    id: "19",
    name: "The Engineer",
    handle: "@ICT_Concepts",
    profileImage: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/ict-yBDsaadzOlXRyhK5VciX2xG3utCA6C.jpg",
    community: "ICT Concepts",
    communityLink: "https://ictconcepts.com",
    markets: ["Forex", "Indices", "Commodities"],
    experience: "10+ years",
    liveTrades: true,
    bestKnownFor: "ICT Concepts",
    tradingStyle: ["Technical Analysis", "Market Structure"],
    verified: true
  }
]